/* generated configuration header file - do not edit */
#ifndef BSP_CLOCK_CFG_H_
#define BSP_CLOCK_CFG_H_
#define BSP_CFG_CLOCKS_SECURE (0)
#define BSP_CFG_CLOCKS_OVERRIDE (0)
#define BSP_CFG_XTAL_HZ (20000000) /* XTAL 20000000Hz */
#define BSP_CFG_HOCO_FREQUENCY (4) /* HOCO 48MHz */
#define BSP_CFG_PLL_SOURCE (BSP_CLOCKS_SOURCE_CLOCK_SUBCLOCK) /* PLL Src: Sub-clock */
#define BSP_CFG_PLL_MUL (BSP_CLOCKS_PLL_MUL(732,00)) /* PLL Mul x732 */
#define BSP_CFG_PLL_FREQUENCY_HZ (11993088) /* PLL 11993088Hz */
#define BSP_CFG_CLOCK_SOURCE (BSP_CLOCKS_SOURCE_CLOCK_HOCO) /* Clock Src: HOCO */
#define BSP_CFG_ICLK_DIV (BSP_CLOCKS_SYS_CLOCK_DIV_2) /* ICLK Div /2 */
#define BSP_CFG_PCLKB_DIV (BSP_CLOCKS_SYS_CLOCK_DIV_32) /* PCLKB Div /32 */
#define BSP_CFG_PCLKD_DIV (BSP_CLOCKS_SYS_CLOCK_DIV_1) /* PCLKD Div /1 */
#define BSP_CFG_CLKOUT_SOURCE (BSP_CLOCKS_CLOCK_DISABLED) /* CLKOUT Disabled */
#define BSP_CFG_CLKOUT_DIV (BSP_CLOCKS_SYS_CLOCK_DIV_1) /* CLKOUT Div /1 */
#define BSP_CFG_SDADC_CLOCK_SOURCE (BSP_CLOCKS_SOURCE_CLOCK_PLL) /* SDADCCLK Src: PLL */
#define BSP_CFG_SDADC_CLOCK_VALUE (11993088) /* SDADCCLK operating clk: 11993088 Hz */
#endif /* BSP_CLOCK_CFG_H_ */
